Integer.__new__(): use isinstance instead of is_Integer.
So that if the user executes Integer(3.14), he gets

    ValueError: invalid argument for Integer: 3.14

instead of

    AttributeError: 'float' object has no attribute 'is_Integer'