unrad added to _tsolve
    Although it would be better if polys would identify radical generators and
    not reject such systems as multivariate polynomials, systems of equations
    that fail polification will get to the fallback which will use _tsolve
    (and hence unrad) so they will now work.

    unrad allows such equations to be solved:
    >>> solve(sqrt(x) - sqrt(x + 1) + sqrt(1 - sqrt(x)))
    [0, 9/16]

    >>> Poly(sqrt(x) - sqrt(x + 1) + sqrt(1 - sqrt(x)))
    Poly(sqrt(-sqrt(x) + 1) - sqrt(x + 1) + sqrt(x), \
    sqrt(-sqrt(x) + 1), sqrt(x + 1), sqrt(x), domain='ZZ')
    >>> roots(_)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "sympy\polys\polyroots.py", line 517, in roots
        raise PolynomialError('multivariate polynomials are not supported')
    sympy.polys.polyerrors.PolynomialError: multivariate polynomials, etc.

    The order that the radicals are processed will determine the output
    (but not, presumably, the final valid roots) so they must be sorted.
    In addition, the terms must be collected so as to collect common
    generators. collect is not suitable for this since it is greedy and
    begins collecting with the first indicated variable. (Perhaps
    collect could use the strategy here to better effect.)

    The checking of solutions was incorrect and that was modified, too.