typing: modernize annotations in polys/ printing/ solvers/ stats/
Modified:
- polys/domains/gaussiandomains.py
- printing/printer.py
- solvers/diophantine/diophantine.py
- solvers/ode/single.py
- stats/rv.py
- tensor/tensor.py

Update type annotations in specified files following PEP 526:
- Convert "# type: X" comments to "variable: X" syntax.
- Replace typing aliases (tDict, tTuple, etc.) with built-in types.
- Add `from __future__ import annotations` for Python 3.8 compatibility.
- Remove redundant None initializations used only for typing.
- Convert Optional[X] to X | None and Union[A, B] to A | B.
- Added ' | None' to type for 'is_real: bool' in stats/rv.py::PSpace

Only remaining typing tType:
- from typing import Sequence as tSequence
- In sympy/stats/stochastic_process_types.py

Most tests pass, and code quality checks have been performed.
Failing local tests  in:
- printing/pretty/tests/test_pretty.py
- printing/tests/test_latex.py
- printing/tests/test_str.py
Due to:
- test_RandomDomain - AttributeError: 'SingleContinuousPSpace' object has no attribute 'is_Finite'
- test_latex_RandomDomain - AttributeError: 'SingleContinuousPSpace' object has no attribute 'is_Finite'
These tests were failing prior to making these changes.

Signed-off-by: Nicholas Laustrup <124007393+nicklaustrup@users.noreply.github.com>