Issues 2203: Replace some "In [n]:/Out[n]:" with ">>>" in doctests.
These doctests was replaced as far as possible.

Turned on:
 ./sympy/solvers/__init__.py: solve(x**5+5*x**4+10*x**3+10*x**2+5*x+1,x)
 ./sympy/integrals/__init__.py: integrate(1/x,x) and so on
 ./doc/src/guide.txt:    In [1]: e = Add(x, x) and so on
 ./doc/src/guide.txt:    In [4]: (x+y*z).args and so on

Leaved without changes:
   (commad `grep  -A 1 --directories=recurse --include=*.* 'In \[' ./`)

by those reasons:

  ./sympy/printing/tree.py  - as order involved, then +SKIP option added.
  ./sympy/geometry/ellipse.py - plotting, +SKIP option added.
  ./sympy/series/gruntz.py  - it is example of debugging.
  ./doc/src/gotchas.txt     - this example of help in IPython (help(), "?").
  ./doc/src/guide.txt       - user's function usage, pretty_printer usage.
! ./doc/src/guide.txt       -  sign(x**2).args
      AttributeError: 'sign' object has no attribute 'agrs'
  ./doc/src/spt-patches/xobj-fix-even-height.patch - do not know what it is.
  ./doc/src/tutorial.txt    - pretty_printer widly usage here.