_int_ methods upgraded; round takes care of last digit better
sympy/core/expr.py

    o add __int__ to expr and raise ValueError if the results might
      be wrong. Since python can represent arbitrarily large ints,
      we can do the translation exactly from sympy expression to int
      via Integer (rather than float which keeps only about 17 digits).

      A result is ambiguous if an expression which is not known to be
      an integer, rounds to a non-zero integer. There is no way (that
      I know of) to chase down the first non-zero decimal digit so the
      burden is placed on the user to pass the expression evaluated
      to the desired number of digits.

    o make __float__ raise a TypeError if the wrong type of input
      was received. This is similar to what is received from Python:

          >>> float(3+4j)
          ...
          TypeError: can't convert complex to float

    o with changes of __float__'s ValueError, __complex__ needs to
     catch TypeError, not ValueError

sympy/core/numbers.py

    o Rational.__int__ does not use float to do the conversion from
      sympy to python as this loses precision:

        >>> big
        12345678901234567890
        >>> big//7
        1763668414462081127
        >>> int(float(Rational(big, 7))) # previous master
        1763668414462081024L
        >>> int(Rational(big, 7)) # now
        1763668414462081127L

    o Integer - add not about using int to process input

    o NumberSymbol - make __int__ a stub and subclass with the
      exact integer output (that doesn't have to depend on evalf).
      Note that evalf(0) only should give the magnitude of the number,
      not the integer value of an expression - evalf uses significant
      digits whereas round uses decimal places. (So it would have been
      appropriate to use round(self) but not self.evalf(0).)

sympy/functions/elementary/miscellaneous.py

    o round() (like evalf) now takes care not to return results to a
      precision higher than the most precise Float in the expression.
      No calculation is done -- this is just a pragmatic limit.

    o it is possible that a value greater than float's limit is
      being calculated, so an attempt to use math's functions is used
      and then a fallback to sympy functions if this fails.

    o there is better handling of the last digit; tests were added for
      this

All lines modified or added are covered with existing tests and those
added in

    sympy/core/tests/test_arit.py
    sympy/functions/elementary/miscellaneous.py
    sympy/core/tests/test_numbers.py

        Added an XFAIL test for issue 3046