Fix a workaround in a test_risch.py test that works now that polys11 is merged
For the rde.py change, I was going to also use .mul_ground() from
polys11, but that doesn't seem to work:

In [1]: Poly(x*t, t).mul_ground(1/x)
...
PolynomialError: 1/x contains an element of the generators set