Rename LANG to LANGUAGES
For some reason, the LANG variables seems to collide with Python, as I am
getting this exception:

ondrej@hawk:~/repos/sympy/doc(master)$ make html
rm -rf sphinx
mkdir -p src/.static
mkdir -p _build/html
mkdir -p _build/doctrees
mkdir -p src/modules
PYTHONPATH=..:/home/ondrej/repos/qsnake/local/lib/python sphinx-build -b html -d _build/doctrees -D latex_paper_size=  src _build/html
Traceback (most recent call last):
  File "/home/ondrej/repos/qsnake/local/bin/sphinx-build", line 8, in <module>
    load_entry_point('Sphinx==1.1', 'console_scripts', 'sphinx-build')()
  File "/home/ondrej/repos/qsnake/local/lib/python2.6/site-packages/Sphinx-1.1-py2.6.egg/sphinx/__init__.py", line 47, in main
    from sphinx import cmdline
  File "/home/ondrej/repos/qsnake/local/lib/python2.6/site-packages/Sphinx-1.1-py2.6.egg/sphinx/cmdline.py", line 18, in <module>
    from docutils.utils import SystemMessage
  File "/home/ondrej/repos/qsnake/local/lib/python2.6/site-packages/docutils/utils.py", line 18, in <module>
    from docutils.error_reporting import ErrorOutput, SafeString
  File "/home/ondrej/repos/qsnake/local/lib/python2.6/site-packages/docutils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/home/ondrej/repos/qsnake/local/lib/python/locale.py", line 480, in getdefaultlocale
    return _parse_localename(localename)
  File "/home/ondrej/repos/qsnake/local/lib/python/locale.py", line 412, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: bg cs de fr ru
make: *** [html] Error 1

This patch makes it work again.