matrices: det_LU_decomposition() handles singular matrices
Addresses issue #12321.
This pull request extends the functionality of
matrices.det_LU_decomposition() so that it returns zero when
passed a singular matrix instead of raising a ValueError.

Current behvior:
>>> A=sympy.Matrix([[1, 2], [1, 2]])
>>> A.det_LU_decomposition()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy/matrices/matrices.py", line 2602, in det_LU_decomposition
    l, u, p = M.LUdecomposition()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy/matrices/matrices.py", line 1333, in LUdecomposition
    combined, p = self.LUdecomposition_Simple(iszerofunc=_iszero)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy/matrices/matrices.py", line 1377, in LUdecomposition_Simple
    raise ValueError("No nonzero pivot found; inversion failed.")
ValueError: No nonzero pivot found; inversion failed.

New behavior:
>>> A=sympy.Matrix([[1, 2], [1, 2]])
>>> A.det_LU_decomposition()
0

This new behavior is implemented by catching the ValueError that
LUdecomposition_Simple() raises when it cannot find a nonzero
pivot, and returning zero from the except statement.
This is not a terribly robust approach, since future versions of
LUdecomposition_Simple() may raise a ValueError for some other reason.
See pull request #12218 for an extension to LUdecomposition_Simple()
that will make det_LU_decomposition() handle all square matrices.