Fix incompatibility with python 2 and the unicode_literals future import.
Testing:

On master, the code fails in the following way, with a confusing error message:
```
>>> from __future__ import unicode_literals
>>> from sympy import *
>>> x = Symbol('x')
>>> lambdify(x, x, modules='numpy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/utilities/lambdify.py", line 358, in lambdify
    buf = _get_namespace(m)
  File "sympy/utilities/lambdify.py", line 477, in _get_namespace
    raise TypeError("Argument must be either a string, dict or module but it is: %s" % m)
TypeError: Argument must be either a string, dict or module but it is: numpy
```

After the changes in this commit are applied, the code works as expected:
```
>>> from __future__ import unicode_literals
>>> from sympy import *
>>> x = Symbol('x')
>>> lambdify(x, x, modules='numpy')
<function <lambda> at 0x1090b86e0>
```