Revert "wip remove hash"
This reverts commit 0bcac53b782b8cd76e58fdb709265c2a98cc3cec.

When the __hash__ is removed an error arises under Python 3.2:

sympy/physics/quantum/tests/test_gate.py:test_UGate ______________
4112  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/sympy/physics/quantum/tests/test_gate.py", line 48, in test_UGate
4113    assert qapply(u1*Qubit('0')) == a*Qubit('0') + c*Qubit('1')
4114  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/sympy/core/decorators.py", line 67, in __sympifyit_wrapper
4115    return func(a, sympify(b, strict=True))
4116  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/sympy/core/decorators.py", line 108, in binary_op_wrapper
4117    return func(self, other)
4118  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/sympy/core/expr.py", line 146, in __mul__
4119    return Mul(self, other)
4120  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/sympy/core/cache.py", line 85, in wrapper
4121    return func_cache_it_cache[k]
4122  File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/sympy/core/basic.py", line 109, in __hash__
4123    h = hash((type(self).__name__,) + self._hashable_content())
4124TypeError: unhashable type: 'MutableDenseMatrix'

This is also reported in issue 880.