[WIP] sympify: Make some minor changes to convert_numpy_types()
Made several minor adjustments to ```convert_numpy_types``` and its doctests.
Because ```numpy``` is required for the doctests, a manual decorator was
added below ```convert_numpy_types```. This seems to not be working because
it isn't getting called when ```convert_numpy_types``` is imported. Further
work is needed.

This commit fails ```bin/doctest sympy/core/sympify.py``` with the following
error:

```
File "sympy/core/sympify.py", line 61, in
    sympy.core.sympify.convert_numpy_types
Failed example:
    convert_numpy_types(numpy.int64(5))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.core.sympify.convert_numpy_types[1]>", line 1, in
        <module>
        convert_numpy_types(numpy.int64(5))
    NameError: name 'numpy' is not defined
**********************************************************************
File "sympy/core/sympify.py", line 64, in
    sympy.core.sympify.convert_numpy_types
Failed example:
    convert_numpy_types(numpy.float32(5))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.core.sympify.convert_numpy_types[2]>", line 1, in
        <module>
        convert_numpy_types(numpy.float32(5))
    NameError: name 'numpy' is not defined
```