Fix polynomials for fixed negative order
This:

  >>> laguerre(-3, 4)
  laguerre(-3, 4)

will no longer raise a:

  ValueError: The index n must be nonnegative integer (got -3)

but instead expand into:

  >>> expand_func(_)
  exp(4)*laguerre(2, -4)

and further:

  >>> expand_func(_)
  17*exp(4)