Update Matrix shape documentation
Documentation to get the shape of a Matrix is outdated. Current documentation causes `ImportError: cannot import name 'shape' from 'sympy'` error. Updated the documentation to use M.shape as opposed to shape(M) function.