8571: raise TypeError for expressions with BooleanAtom
closes #8571
closes #8441
closes #10569

The _op_priority of BooleanAtom is set to 1 greater than Expr so
its __r*__ methods get called first and allow a consistent
TypeError to be raised for expressions involving S.true or S.false.
In cases where BooleanAtom's r-ops aren't called, Python already
emits a TypeError. This means that in those cases the __* routines
don't need to be defined, but they are there in case unforseen
expressions end up calling them.  Here are cases where an already
existing TypeError is raised:

>>> o=1
>>> t=S.true
>>> +t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary +: 'BooleanTrue'
>>> abs(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for abs(): 'BooleanTrue'
>>> t//o
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for //: 'BooleanTrue' and 'int'
>>> o//t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for //: 'int' and 'BooleanTrue'
>>> o%t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for %: 'int' and 'BooleanTrue'
>>> divmod(t,o)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for divmod(): 'BooleanTrue' and 'int'
>>> divmod(o,t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for divmod(): 'int' and 'BooleanTrue'
>>> int(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string or a number, not 'BooleanTrue'