Add lambdified functions to the Python linecache
This allows things like inspect.getsource (?? in IPython) to work, and the
code will show up in the tracebacks in IPython.

Presently, the docstring is not included in the source code, because it is
added after the function is execed.

Example:

In [1]: f = lambdify(x, 1/x)

In [2]: f(0)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-2-6bfbdbfff9c4> in <module>()
----> 1 f(0)

<lambdifygenerated-1> in _lambdifygenerated(x)
      1 def _lambdifygenerated(x):
----> 2     return (1/x)

ZeroDivisionError: division by zero

In [3]: f??
Signature: f(x)
Docstring:
Created with lambdify. Signature:

func(x)

Expression:

1/x

Source code:

def _lambdifygenerated(x):
    return (1/x)

Imported modules:
Source:
def _lambdifygenerated(x):
    return (1/x)
File:      ~/Documents/Python/sympy/sympy/<lambdifygenerated-1>
Type:      function