Updating #18543
To overcome the problem limit_seq - AttributeError: 'NoneType' object has no attribute 'is_comparable' #18543
the present step should be taken ....
If L2 is not none, then only the comparision is possible else there will be error as shown in #18543
Hence , this is fixed by the above simple if loop, as modified above..