Prevent substitution inside Derivative in some cases
Currently, a substitution such as Derivative(f(x, y), y).subs(y, x) results in
Derivative(f(x, x), x) which is a different derivative. This affects the computation
of derivatives of orders 2 or greater of expressions with undefined functions.
This commit modifies _eval_subs method of Derivative class to disallow substitution
when it is clearly wrong. Fixes #13791; also fixes #13795.

Substitution (old, new) cannot be done inside Derivative(expr, vars) if it is:
1. changing expr by introducing a variable among vars, or
2. changing vars by introducing a variable contained in expr
Exception: complete replacement of expr by new (expr == old) is always allowed,
so for example Derivative(f(x), x).subs(f(x), y).subs(y, f(x)) results in
Derivative(f(x), x) although one may call this abuse of notation.