add table method to Matrix
>>> m.table()
[x, (x + 1)/a]
[3,       x/3]

>>> m.table(colsep=' ')
[x (x + 1)/a]
[3       x/3]

There are a couple of troubling test failures that were fixed but might
indicate a problem: in some of the mechanics test, functions started getting
printed with their argument, e.g. `u(t)` instead of just `u`. And then
these two failures:

_______________________________________________________________________________
_______________________ sympy.matrices.matrices.classof _______________________
File "sympy\matrices\matrices.py", line 3737, in sympy.mat
rices.matrices.classof
Failed example:
    classof(M, IM)
Exception raised:
    Traceback (most recent call last):
      File "C:\Python27\lib\doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.matrices.matrices.classof[4]>", line 1, in <module>
        classof(M, IM)
      File "sympy\sympy\interactive\printing.py", line 17, in _d
isplayhook
        print stringify_func(arg)
      File "sympy\sympy\printing\str.py", line 568, in sstrrepr
        s = p.doprint(expr)
      File "sympy\sympy\printing\printer.py", line 230, in dopri
nt
        return self._str(self._print(expr))
      File "sympy\sympy\printing\printer.py", line 247, in _prin
t
        return getattr(expr, self.printmethod)(self, *args)
    TypeError: unbound method <lambda>() must be called with Matrix instance as
first argument (got StrReprPrinter instance instead)

SOLUTION:

Adding a print before the call to classof solved the problem.
And in the test below, removing the print solved the problem.

_______________________________________________________________________________
________________________ sympy.solvers.solvers.nsolve _________________________
File "sympy\sympy\solvers\solvers.py", line 1884, in sympy.solve
rs.solvers.nsolve
Failed example:
    print nsolve((f1, f2), (x1, x2), (-1, 1))
Exception raised:
    Traceback (most recent call last):
      File "C:\Python27\lib\doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.solvers.solvers.nsolve[8]>", line 1, in <module>
        print nsolve((f1, f2), (x1, x2), (-1, 1))
      File "sympy\sympy\solvers\solvers.py", line 1951, in nsolv
e
        x = findroot(f, x0, J=J, **kwargs)
      File "C:\Users\leslie\sympy\sympy\mpmath\calculus\optimization.py", line 9
28, in findroot
        fx = f(x0[0])
    TypeError: <lambda>() takes exactly 2 arguments (1 given)