Fix repetend notation for leading zeros
    The repetend notation for 1/19 can be written as
    S('.[052631578947368421]') but this raised a parsing error:

    sympy.core.sympify.SympifyError: SympifyError:
    "Cannot parse u'(0+0*1/1+052631578947368421*1/999999999999999999)'."

    which has a leading 0 in front of the 5. By stripping these the
    sympification works again. Tests added.