Do not crash if the latex preamble contains comments
Previously this interpreted % symbols in the preamble as string formatting markers.
This failed for the same reason as the following does:
```python
>>> def concat_badly(a, b):
...     return (a + " + %s") % b
>>> concat_badly("a", "b")
'a + b'
>>> concat_badly("a % 2", "b")
ValueError: unsupported format character ' ' (0x20) at index 5
```

Also remove some python 2 compatibility which is now a no-op