Totative: ValueError for non-Integer,non-Symbols
The totative function should raise ValueError for the input
which is non-Integer or non-Symbol.
Ex.

In [1]: from sympy.ntheory.factor_ import totative
In [2]: print(totative(3.4))
Out [2]: Traceback (most recent call last):
           File "factor_.py", line 1485, in <module>
             print(totient(3.4))
           File "/usr/local/lib/python3.4/dist-packages/sympy/core/cache.py", line 91, in wrapper
             retval = cfunc(*args, **kwargs)
           File "/usr/lib/python3.4/functools.py", line 452, in wrapper
             result = user_function(*args, **kwds)
           File "/usr/local/lib/python3.4/dist-packages/sympy/core/function.py", line 375, in __new__
             result = super(Function, cls).__new__(cls, *args, **options)
           File "/usr/local/lib/python3.4/dist-packages/sympy/core/cache.py", line 91, in wrapper
             retval = cfunc(*args, **kwargs)
           File "/usr/lib/python3.4/functools.py", line 452, in wrapper
             result = user_function(*args, **kwds)
           File "/usr/local/lib/python3.4/dist-packages/sympy/core/function.py", line 199, in __new__
             evaluated = cls.eval(*args)
           File "factor_.py", line 1416, in eval
             raise ValueError("n must be a postive integer")
         ValueError: n must be a postive integer
In [3]: print(totative(17))
Out [3]: 16

Earlier earlier for non-Integers the function was returned unevaluated