rename __evalf to _evalf_
Curiously, the name __evalf causes an error:

  File "sympy\core\evalf.py", line 1318, in evalf
      result = __evalf(self, prec + 4, options)
      NameError: global name '_EvalfMixin__evalf' is not defined

The name _evalf_ does not cause the same error.