Give a better warning in Basic.__call__
Now, instead of getting

>>> (x + y)(x - y)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: 'Add' object is not callable

You will see

>>> (x + y)(x - y)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 394, in __call__
    raise TypeError("'%s' object is not callable. Perhaps you forgot a '*'?" % self.__class__.__name__)
TypeError: 'Add' object is not callable. Perhaps you forgot a '*'?