pretty: fix xobj for even height
Previously pprint({x**2: 1}) was failing with cryptic exception

    ValueError: xobj: expect length = 2*k+1

And this is a wrong approach.

Things need to just work, so I've modified xobj to tweak evenly heighted
objects somewhat. After all it looks good, so why not?

In [1]: [x**2]
Out[1]:
⎡ 2⎤
⎣x ⎦

In [2]: (x**2,)
Out[2]:
⎛ 2⎞
⎝x ⎠

In [3]: {x**2: 1}
Out[3]:
⎧ 2   ⎫
⎨x : 1⎬
⎩     ⎭