Included test
Added test case for the input which was causing the error in issue
#11062:

‘from sympy import *
from sympy.simplify.trigsimp import *
from sympy.abc import x,y
trigsimp_groebner(csc(x) * sin(x))’

Previously Poly function wasn’t imported in the trigsimp.py file hence
there was an error :
NameError: name 'Poly' is not defined

importing the Poly function in the file solves the problem :)