stats: Minor changes in parameter handling
Changed the condition from checking if not parameter.is_positive to
if not parameter > 0. This is to prevent the AttributeError: 'int' object
has no attribute 'is_positive'